### ISSUE TITLE
Errors in _rawtooltips

### ISSUE THREAD

**Issue by BmElectro** [TheDrone7/shieldbow#2]
There are some errors in _rawtooltips, the errors are kinda separated into categories: 

1. Calculation errors e.g. Viego Q:
![viegoq](https://user-images.githubusercontent.com/42422351/167500724-52eb8f50-27cc-4108-b90a-2ff78661fc3e.png)
As we see the scaling are way off, another example is Katarina's R, Kled W. 

2. Errors that seem like placeholders should be replaced e.g. Malhpite W.
![MalphiteW](https://user-images.githubusercontent.com/42422351/167501437-7fea187c-d76c-4faf-b1a9-632ca8ca44a3.png)
Here the %i:scaleArmor% should be replaced, other examples include RengarQ. 

3. Champions that have some sort of stacking mechanisim or internal scaling default to a "?" question mark since judging by the code replacements are not found. e.g. Kindred QWE (stacks), Thresh WE, Ziggs W, Gangplank E, Draven R, MissFortune W. 

4. Since the tooltips are taken from in-game as it seems there are specific "interactive parts" that work correctly in-game but make no sense for a tooltip ment to be displayed as info text and they are getting switched to "?". e.g. BardW (Chimes Counter), Kaisa (QWE, stats counter)

**Comment by TheDrone7** [comment]
1. The numbers are actually correct. I did find them off while testing them but when I matched them with the Wiki, they turned out to be correct (they seem like a lot but if you actually calculate them all (% means gotta divide by 100) they are all as they were supposed to be.
2. The data for these placeholders, was simply unavailable. There's another kind of placeholders where the format is `{ fn }` and `n` is some random number. Again, no provided data. Data dragon does not provide any values for placeholders at all, I fetcht hem from community dragon and appropriately replace them but thanks to the inconsistencies, some stuff just nobody knows.
3. Same as above, the `?` are actually another kind of placeholders that simply had no data.
